#!/usr/bin/env bash
# Summary: a fake `dart` CLI that delegate the actual dart CLI.

set -e

if [[ "$1" = "--debug" ]]; then
    export FENV_DEBUG=1
    shift
fi

[[ -n "$FENV_DEBUG" ]] && set -x

dart_cli=$(fenv-which dart)
dart_cli_dir="$(dirname "$dart_cli")"
# Fake the PATH as if "$dart_cli_dir" is located at the top of the PATH.
$dart_cli $@
