#!/usr/bin/env bash
# Summary: a fake `dart` CLI that delegate the actual dart CLI.

set -e

if [[ "$1" = "--debug" ]]; then
    export FENV_DEBUG=1
    shift
fi

if [[ -n "$FENV_DEBUG" ]]; then
    # https://wiki-dev.bash-hackers.org/scripting/debuggingtips#making_xtrace_more_useful
    export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -x
fi

dart_cli=$(fenv which dart)
dart_cli_dir="$(dirname "$dart_cli")"
# Fake the PATH as if "$dart_cli_dir" is located at the top of the PATH.
$dart_cli $@
