[target.x86_64-unknown-linux-musl]
xargo = { version = "0.0.0" }
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:0.2.5"
pre-build = "apt-get update && apt-get install -y libssl-dev"

[target.aarch64-unknown-linux-musl]
xargo = { version = "0.0.0" }
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:0.2.5"
pre-build = "apt-get update && apt-get install -y libssl-dev"