[target.x86_64-unknown-linux-musl]
xargo = false
pre-build = "apt-get update && apt-get install -y libssl-dev"

[target.aarch64-unknown-linux-musl]
xargo = false
pre-build = "apt-get update && apt-get install -y libssl-dev"