#!/usr/bin/env bash
# Summary: reads the version code written in the given version file.
# Usage: fenv version-file-read <file>

set -e
[ -n "$FENV_DEBUG" ] && set -x

function abort() {
  >&2 echo "fenv: "$@
  exit 1
}

function is_version_safe() {
  # As needed, check that the constructed path exists as a child path of PYENV_ROOT/versions
  version="$1"
  [[ "$version" =~ ^[0-9]+([.][0-9]+([.][0-9]+)?)?$ ]]
}

if [[ "$#" -ne 1 ]]; then
  abort "usage: fenv version-file-read <file>"
fi

version_file="$1"

if ! [[ -f "$version_file" ]]; then
  abort "'$version_file' does not exist."
elif ! [[ -s "$version_file" ]]; then
  abort "'$version_file' is empty."
fi

oldifs="$IFS"

IFS=":"
lines=( $(cat "$version_file") )
IFS="$oldifs"

if is_version_safe "${lines[0]}"; then
  echo "${lines[0]}"
else
  abort "an invalid version code: '${lines[0]}'"
fi
