#!/usr/bin/env bash
# Summary: Internal utility that displays the locall-installed flutter sdk's
# version corresponding to the given version file.
# Usage: fenv--local-sdk-version <version-file>

set -eo errexit
[[ -n "$FENV_DEBUG" ]] && set -x

local_sdk_dir=$(fenv--local-sdk-dir "$1")

if [[ -r "$local_sdk_dir/version" ]]; then
  cat "$local_sdk_dir/version"
fi
