#!/usr/bin/env bash
# Usage: fenv version-file [<dir>]
# Summary: Show the currently selected Flutter SDK version only.

set -eo errexit
[[ -n "$FENV_DEBUG" ]] && set -x

function abort() {
  >&2 echo "fenv: "$@
  exit 2
}

version_file=$(fenv-version-file)
if ! [[ -f "$version_file" ]]; then
  abort "No selected flutter sdk"
fi

if fenv--is-global "$version_file"; then
  # when the global version file
  version=$(fenv-version-file-read "$version_file")
  if [[ -d "$FENV_ROOT/versions/$version" ]]; then
    echo $version
  elif resolved_version=$(fenv-latest --quiet "$version"); then
    echo $resolved_version
  else
    abort "version '$version' is not installed (set by $version_file)"
  fi
else
  # when a local version file
  fenv--ensure-local-version "$version_file"
  fenv-version-file-read "$version_file"
fi
