#!/usr/bin/env bash
# Summary: Display prefixes for flutter version
# Usage: fenv prefix [<version>]
#
# Displays the directory where the given flutter version is installed.
# If no version is given, `fenv prefix' displays the locations of the currently
# selected version.

set -e

[[ -n "$FENV_DEBUG" ]] && set -x

if [[ "$#" -eq 0 ]]; then
  version=$(fenv-version-name)
else
  version=$1
fi

if [[ -d "$FENV_ROOT/versions/$version" ]]; then
  echo "$FENV_ROOT/versions/$version"
elif resolved_version=$(fenv-latest --quiet "$version"); then
  echo "$FENV_ROOT/versions/$resolved_version"
else
  echo "fenv: warning: version '$version' is not installed"
  exit 1
fi
