#!/usr/bin/env bash
#
# Summary: Set or show the global flutter version
#
# Usage: fenv global <version>
#
# Sets the global flutter version. You can override the global version at
# any time by setting a directory-specific version with `fenv local'.

set -e
[[ -n "$FENV_DEBUG" ]] && set -x

if [[ -n "$1" ]]; then
  fenv-version-file-write "$FENV_ROOT/version" "$1"
elif [[ -f "$FENV_ROOT/version" ]]; then
  fenv-version-file-read "$FENV_ROOT/version"
else
  >&2 echo "fenv: no specified global version."
  exit 2
fi
