#!/usr/bin/env bash
# Summary: A utility CLI to convert a path to the absolute path

set -e
[[ -n "$FENV_DEBUG" ]] && set -x

target_path=$1
if [[ -d "$target_path" ]]; then
    echo "$(cd $target_path && pwd)"
elif [[ -f "$target_path" ]]; then
    echo "$(cd "$(dirname "$target_path")" && pwd)/$(basename "$target_path")"
else
    >&2 echo "fenv: No such file or directory"
    exit 2
fi
