#!/usr/bin/env bash
# Summary: Internal utility that ensure the local version and the
#          locally-installed the specific flutter sdk version is matched.
# Usage: fenv--ensure-local-version <version-file>

set -eo errexit
[[ -n "$FENV_DEBUG" ]] && set -x

function abort() {
  >&2 echo "fenv: "$@
  exit 2
}

version_file="$1"

version=$(fenv-version-file-read "$version_file")
local_sdk_version=$(fenv--local-sdk-version "$version_file")

# Check the locally downloaded flutter sdk directory.
if [[ "$version" == "$local_sdk_version" ]]; then
  exit 0
fi

if ! [[ -f "$(fenv--local-sdk-dir "$version_file")" ]]; then
  # Ensure the flutter sdk "$version" is installed.
  set +e
  error_message=$(fenv-latest "$version" 2>&1 > /dev/null)
  exitcode=$?
  set -e

  if [[ "$exitcode" -ne 0 ]]; then
    >&2 echo "$error_message: try to execute 'fenv install && fenv local --symlink'"
    exit $exitcode
  fi
fi
abort "unmatched local version: execute 'fenv local --symlink'"
