#!/usr/bin/env bash
# Usage: fenv version-file [<dir>]
# Summary: Detect the file that sets the current fenv version

set -e
[[ -n "$FENV_DEBUG" ]] && set -x

target_dir="$1"

function find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -f "${root}/.flutter-version" ]; then
      echo "${root}/.flutter-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [[ -n "$target_dir" ]]; then
  if ! [[ -d "$target_dir" ]]; then
    >&2 echo "fenv: a directory '$target_dir' does not exist."
    exit 2
  fi
  find_local_version_file "$target_dir"
else
  find_local_version_file "$FENV_DIR" || {
    [ "$FENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${FENV_ROOT}/version"
fi
