#!/usr/bin/env bash
# Summary: Show Flutter SDK version 

set -e
[[ -n "$FENV_DEBUG" ]] && set -x

exitcode=0
version_name=$(fenv-version-name) || exitcode=$?

if [[ -n "$version_name" ]]; then
  echo "$version_name (set by $(fenv-version-file))"
fi
exit $exitcode
