#!/usr/bin/env bash
# Summary: An internal utility to test whether the given version file path is
# the global version file.
# If yes, exit with zero. Otherwise, exit with non-zero.
# Usage: fenv--is-global <version-file>

set -eo errexit
[[ -n "$FENV_DEBUG" ]] && set -x

[[ "$1" == "$FENV_ROOT/version" ]]
