#!/usr/bin/env bash
# Summary: Lists up the downloaded flutter SDK versions.

set -e
[[ -n "$FENV_DEBUG" ]] && set -x

fenv_versions=$FENV_ROOT/versions

if ! [[ -d "$fenv_versions" ]]; then
  >&2 echo "fenv: check whether did 'fenv init'"
  exit 1
fi

version_list=$(ls -1 $fenv_versions)
if [[ -z "$version_list" ]]; then
  >&2 echo "fenv: no installed flutter sdk"
else
  ls -1 $fenv_versions
fi
